<Project Sdk="Godot.NET.Sdk/4.5.1">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<TargetFramework Condition="'$(GodotTargetPlatform)' == 'android'">net9.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<PlatformTarget>x64</PlatformTarget>
		<Prefer32Bit>false</Prefer32Bit>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GameCore\GameCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\Lib\ML_Lib.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
