<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
	<OutputType>Exe</OutputType>
	<UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameCore\GameCore.csproj" />
    </ItemGroup>
	<ItemGroup>
		<None Include="..\Lib\ML_Lib.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
